CREATE TABLE order_cancellation_logs
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    rider_id     BIGINT                                  NOT NULL,
    reason       VARCHAR(255)                            NOT NULL,
    cancelled_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_order_cancellation_logs PRIMARY KEY (id)
);