CREATE TABLE customer_order_cancellations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    customer_id  BIGINT                                  NOT NULL,
    reason       VARCHAR(255),
    cancelled_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_customer_order_cancellations
        PRIMARY KEY (id),

    CONSTRAINT uk_customer_order_cancellations_order
        UNIQUE (order_id),

    CONSTRAINT fk_customer_order_cancellations_order
        FOREIGN KEY (order_id)
            REFERENCES orders (id),

    CONSTRAINT fk_customer_order_cancellations_customer
        FOREIGN KEY (customer_id)
            REFERENCES customers (id)
);