CREATE TABLE kitchen_managers (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  user_id BIGINT NOT NULL UNIQUE,
                                  restaurant_id BIGINT NOT NULL UNIQUE,

                                  CONSTRAINT fk_kitchen_manager_user
                                      FOREIGN KEY (user_id) REFERENCES users(id),

                                  CONSTRAINT fk_kitchen_manager_restaurant
                                      FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
);