CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE addon_groups
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    min_selections INTEGER                                 NOT NULL,
    max_selections INTEGER                                 NOT NULL,
    CONSTRAINT pk_addon_groups PRIMARY KEY (id)
);

CREATE TABLE addresses
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street         VARCHAR(255),
    building       VARCHAR(255),
    floor          VARCHAR(255),
    apartment      VARCHAR(255),
    customer_id    BIGINT                                  NOT NULL,
    governorate_id BIGINT,
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE admins
(
    user_id      BIGINT NOT NULL,
    name         VARCHAR(255),
    phone_number VARCHAR(255),
    CONSTRAINT pk_admins PRIMARY KEY (user_id)
);

CREATE TABLE banners
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    image_url    VARCHAR(255),
    redirect_url VARCHAR(255),
    active       BOOLEAN,
    CONSTRAINT pk_banners PRIMARY KEY (id)
);

CREATE TABLE cart_addons
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity           INTEGER,
    price_at_addition  DOUBLE PRECISION,
    cart_item_id       BIGINT                                  NOT NULL,
    menu_item_addon_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_cart_addons PRIMARY KEY (id)
);

CREATE TABLE cart_items
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity             INTEGER,
    special_instructions TEXT,
    item_total_price     DOUBLE PRECISION,
    cart_id              BIGINT                                  NOT NULL,
    menu_item_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id   BIGINT                                  NOT NULL,
    restaurant_id BIGINT,
    subtotal      DOUBLE PRECISION,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    description   TEXT,
    is_active     BOOLEAN DEFAULT TRUE                    NOT NULL,
    restaurant_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE coupons
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code           VARCHAR(255),
    discount_value DOUBLE PRECISION,
    discount_type  VARCHAR(255),
    expiry_date    TIMESTAMP WITHOUT TIME ZONE,
    active         BOOLEAN,
    CONSTRAINT pk_coupons PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id             BIGINT NOT NULL,
    name           VARCHAR(255),
    loyalty_points INTEGER,
    phone_number   BIGINT,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE drivers
(
    user_id        BIGINT NOT NULL,
    name           VARCHAR(255),
    vehicle_type   VARCHAR(255),
    license_number VARCHAR(255),
    is_online      BOOLEAN,
    phone_number   BIGINT,
    national_id    VARCHAR(255),
    CONSTRAINT pk_drivers PRIMARY KEY (user_id)
);

CREATE TABLE governorates
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_governorates PRIMARY KEY (id)
);

CREATE TABLE historical_order_item_addons
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_item_id BIGINT                                  NOT NULL,
    addon_name    VARCHAR(255)                            NOT NULL,
    addon_price   DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_historical_order_item_addons PRIMARY KEY (id)
);

CREATE TABLE menu_item_addon_groups
(
    addon_group_id BIGINT NOT NULL,
    menu_item_id   BIGINT NOT NULL
);

CREATE TABLE menu_item_addons
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    additional_price DOUBLE PRECISION                        NOT NULL,
    is_available     BOOLEAN DEFAULT TRUE                    NOT NULL,
    addon_group_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_menu_item_addons PRIMARY KEY (id)
);

CREATE TABLE menu_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  TEXT,
    base_price   DOUBLE PRECISION                        NOT NULL,
    image_url    VARCHAR(255),
    is_available BOOLEAN DEFAULT TRUE                    NOT NULL,
    category_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_menu_items PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    menu_item_id BIGINT                                  NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    unit_price   DOUBLE PRECISION                        NOT NULL,
    notes        TEXT,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id    BIGINT                                  NOT NULL,
    restaurant_id  BIGINT                                  NOT NULL,
    rider_id       BIGINT,
    address_id     BIGINT                                  NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    payment_method VARCHAR(255)                            NOT NULL,
    delivery_fee   DECIMAL                                 NOT NULL,
    total_price    DECIMAL                                 NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount         DOUBLE PRECISION,
    payment_method VARCHAR(255),
    payment_status VARCHAR(255),
    payment_date   TIMESTAMP WITHOUT TIME ZONE,
    order_id       BIGINT,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE promotions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255),
    description    VARCHAR(255),
    discount_value DOUBLE PRECISION,
    start_date     TIMESTAMP WITHOUT TIME ZONE,
    end_date       TIMESTAMP WITHOUT TIME ZONE,
    active         BOOLEAN,
    restaurant_id  BIGINT,
    CONSTRAINT pk_promotions PRIMARY KEY (id)
);

CREATE TABLE restaurant_categories
(
    category_id   BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    CONSTRAINT pk_restaurant_categories PRIMARY KEY (category_id, restaurant_id)
);

CREATE TABLE restaurants
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    phone          VARCHAR(255)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    address        VARCHAR(255)                            NOT NULL,
    governorate_id BIGINT                                  NOT NULL,
    description    TEXT,
    logo_url       VARCHAR(255),
    is_active      BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_restaurants PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE reviews
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating        INTEGER,
    comment       VARCHAR(255),
    customer_id   BIGINT,
    restaurant_id BIGINT,
    order_id      BIGINT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE wallet_transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount           DOUBLE PRECISION,
    transaction_type VARCHAR(255),
    transaction_date TIMESTAMP WITHOUT TIME ZONE,
    description      VARCHAR(255),
    wallet_id        BIGINT,
    CONSTRAINT pk_wallet_transactions PRIMARY KEY (id)
);

CREATE TABLE wallets
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance DOUBLE PRECISION,
    user_id BIGINT,
    CONSTRAINT pk_wallets PRIMARY KEY (id)
);

ALTER TABLE carts
    ADD CONSTRAINT uc_carts_customer UNIQUE (customer_id);

ALTER TABLE coupons
    ADD CONSTRAINT uc_coupons_code UNIQUE (code);

ALTER TABLE governorates
    ADD CONSTRAINT uc_governorates_name UNIQUE (name);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_order UNIQUE (order_id);

ALTER TABLE restaurants
    ADD CONSTRAINT uc_restaurants_email UNIQUE (email);

ALTER TABLE restaurants
    ADD CONSTRAINT uc_restaurants_phone UNIQUE (phone);

ALTER TABLE reviews
    ADD CONSTRAINT uc_reviews_order UNIQUE (order_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE wallets
    ADD CONSTRAINT uc_wallets_user UNIQUE (user_id);

ALTER TABLE addresses
    ADD CONSTRAINT FK_ADDRESSES_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE addresses
    ADD CONSTRAINT FK_ADDRESSES_ON_GOVERNORATE FOREIGN KEY (governorate_id) REFERENCES governorates (id);

ALTER TABLE admins
    ADD CONSTRAINT FK_ADMINS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);

ALTER TABLE cart_addons
    ADD CONSTRAINT FK_CART_ADDONS_ON_CART_ITEM FOREIGN KEY (cart_item_id) REFERENCES cart_items (id);

ALTER TABLE cart_addons
    ADD CONSTRAINT FK_CART_ADDONS_ON_MENU_ITEM_ADDON FOREIGN KEY (menu_item_addon_id) REFERENCES menu_item_addons (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES carts (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_MENU_ITEM FOREIGN KEY (menu_item_id) REFERENCES menu_items (id);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);

ALTER TABLE drivers
    ADD CONSTRAINT FK_DRIVERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE historical_order_item_addons
    ADD CONSTRAINT FK_HISTORICAL_ORDER_ITEM_ADDONS_ON_ORDER_ITEM FOREIGN KEY (order_item_id) REFERENCES order_items (id);

ALTER TABLE menu_items
    ADD CONSTRAINT FK_MENU_ITEMS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE menu_item_addons
    ADD CONSTRAINT FK_MENU_ITEM_ADDONS_ON_ADDON_GROUP FOREIGN KEY (addon_group_id) REFERENCES addon_groups (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_RIDER FOREIGN KEY (rider_id) REFERENCES drivers (user_id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_MENU_ITEM FOREIGN KEY (menu_item_id) REFERENCES menu_items (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE promotions
    ADD CONSTRAINT FK_PROMOTIONS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);

ALTER TABLE restaurants
    ADD CONSTRAINT FK_RESTAURANTS_ON_GOVERNORATE FOREIGN KEY (governorate_id) REFERENCES governorates (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);

ALTER TABLE wallets
    ADD CONSTRAINT FK_WALLETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE wallet_transactions
    ADD CONSTRAINT FK_WALLET_TRANSACTIONS_ON_WALLET FOREIGN KEY (wallet_id) REFERENCES wallets (id);

ALTER TABLE menu_item_addon_groups
    ADD CONSTRAINT fk_meniteaddgro_on_addon_group FOREIGN KEY (addon_group_id) REFERENCES addon_groups (id);

ALTER TABLE menu_item_addon_groups
    ADD CONSTRAINT fk_meniteaddgro_on_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items (id);

ALTER TABLE restaurant_categories
    ADD CONSTRAINT fk_rescat_on_categories FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE restaurant_categories
    ADD CONSTRAINT fk_rescat_on_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);