CREATE TABLE IF NOT EXISTS otp_verification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255),
    otp_hash      VARCHAR(255),
    expires_at    TIMESTAMP WITHOUT TIME ZONE,
    attempt_count INTEGER                                 NOT NULL,
    verified      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_otp_verification PRIMARY KEY (id)
    );