CREATE TABLE otp_verification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255),
    otp_hash      VARCHAR(255),
    expires_at    TIMESTAMP WITHOUT TIME ZONE,
    attempt_count INTEGER                                 NOT NULL,
    verified      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_otpverification PRIMARY KEY (id)
);

ALTER TABLE users
    ADD otp VARCHAR(255);

ALTER TABLE users
    ADD otp_expiration TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD password_reset_token VARCHAR(255);

ALTER TABLE users
    ADD password_reset_token_expiration TIMESTAMP WITHOUT TIME ZONE;