CREATE TABLE IF NOT EXISTS wallet_transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount           DOUBLE PRECISION,
    transaction_type VARCHAR(255),
    transaction_date TIMESTAMP WITHOUT TIME ZONE,
    description      VARCHAR(255),
    wallet_id        BIGINT,
    CONSTRAINT pk_wallet_transactions PRIMARY KEY (id),
    CONSTRAINT fk_wallet_transactions_wallet
        FOREIGN KEY (wallet_id) REFERENCES wallets (id)
);
