spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/talabaty_db
spring.datasource.username=postgres
spring.datasource.password=Postgres123!
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
